config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :companies do
    resources :users, only: [:index]
  end

  resources :tweets, only: [:index] do
    collection do
      get :report # GET /tweets/report
    end
  end

  resources :users, only: [:index, :show] do
    resources :tweets, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy, inverse_of: :company
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, inverse_of: :tweets

  scope :by_user_id, -> (user_id) { where(user_id: user_id) if user_id.present? }
end

app/models/user.rb
class User < ApplicationRecord
after_create :send_create_user

  belongs_to :company, inverse_of: :users
  has_many :tweets, dependent: :destroy, inverse_of: :user

  scope :by_company, -> (identifier) { where(company: identifier) if identifier.present? }
  scope :by_username, -> (username) { where('UPPER(username) LIKE UPPER(?)', "%#{username}%") if username.present? }

  private

  def send_create_user
    UserMailer.create_user(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  def index
    @companies = Company.all

    respond_to do |format|
      format.html # renderiza app/views/companies/index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  def show; end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit; end

  # POST /companies
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Empresa criada com sucesso.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Empresa atualizada com sucesso.' }
        format.json { render json: @company }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_path, notice: 'Empresa excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

    def set_company
      @company = Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    limit = (params[:limit] || 10).to_i
    cursor = params[:cursor]

    tweets = Tweet.by_user_id(params[:user_id])

    if cursor
      tweets = tweets.where('created_at < ?', Time.iso8601(cursor)).order(created_at: :desc).limit(limit)
    else
      tweets = tweets.order(created_at: :desc).limit(limit)
    end

    next_cursor = tweets.last&.created_at&.iso8601

    render json: {
      tweets: tweets,
      next_cursor: next_cursor
    }
  end

  def report
    ReportGenerationJob.perform_async()
    head :ok
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    users = User.by_company(params[:company_id])
                .by_username(search_params[:username])
                
    render json: users.all
  end

  private

  def search_params
    params.permit(:username)
  end

end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% else %>
    <div class="field">
      <%= form.label :name, "Nome da empresa" %><br>
      <%= form.text_field :name %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editar Companhia</h1>

<%= render 'form', company: @company %>

<%= link_to 'Visualizar', @company %> |
<%= link_to 'Voltar', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companhias</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.id %></td>
        <td><%= company.name %></td>
        <td><%= link_to 'Visualizar', company, class: 'btn btn-sm btn-outline-primary' %></td>
        <td><%= link_to 'Editar', edit_company_path(company), class: 'btn btn-sm btn-outline-warning' %></td>
        <td><%= link_to 'Excluir', company, method: :delete, class: 'btn btn-sm btn-outline-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Companhia', new_company_path, class: 'btn btn-success' %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Voltar', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Detalhes da Companhia</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @company.id %></td>
      <td><%= @company.name %></td>
    </tr>
  </tbody>
</table>

<div class="actions">
  <%= link_to 'Editar', edit_company_path(@company), class: 'btn btn-primary' %>
  <%= link_to 'Voltar', companies_path, class: 'btn btn-secondary' %>
</div>